name: Frontend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from github
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Install frontend dependencies
      - run: cd starter/frontend && npm ci

      # Run the tests.
      - run: cd starter/frontend && npm test

      # Log message at complete
      - run: |
          echo "Done test step without error"

  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from github
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Install frontend dependencies
      - run: cd starter/frontend && npm ci

      # Run the linter
      - run: cd starter/frontend && npm run lint

      # Log message at complete
      - run: |
          echo "Done lint step without error"

  build:
    runs-on: ubuntu-latest

    if: ${{ always() && needs.test.result == 'success' && needs.lint.result == 'success' }}

    needs: [test, lint]

    environment:
      name: DEV

    steps:
      # Check out the code from github
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Install frontend dependencies
      - run: cd starter/frontend && npm ci

      # Build source code
      - run: cd starter/frontend && npm run build

      # Build and push FE to Docker hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: starter/frontend
          push: true
          tags: ttx412/mp-frontend:latest

      # Log message at complete
      - run: |
          echo "Done build step without error"
